---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/preparation
      - name: Test
        run: uv run pytest
      - name: Attach Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

      # add API token to `CODACY_PROJECT_TOKEN` action secrets
      - name: Generate XML Coverage Report
        run: uv run coverage xml
      - name: Submit Coverage Report
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

  build:
    name: Test Python package build
    runs-on: ubuntu-latest
    needs:
      - test
    services:
      redis:
        image: docker.io/redis:8
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/preparation
      - name: Build
        run: uv build
      - name: Smoke test (wheel)
        run: uv run --isolated --with dist/*.whl tests/smoke_test_rq.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --with dist/*.tar.gz tests/smoke_test_rq.py
